[2025-04-12T13:21:04.574+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-12T13:21:04.581+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-12T13:21:04.582+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-12T13:21:04.593+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_bertopic> on 2025-04-06 00:00:00+00:00
[2025-04-12T13:21:04.605+0000] {standard_task_runner.py:60} INFO - Started process 54165 to run task
[2025-04-12T13:21:04.609+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_comment_analysis_pipeline', 'run_bertopic', 'manual__2025-04-06T00:00:00+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/Sentiment_Topicmodelling.py', '--cfg-path', '/tmp/tmpkd5gqhrj']
[2025-04-12T13:21:04.611+0000] {standard_task_runner.py:88} INFO - Job 230: Subtask run_bertopic
[2025-04-12T13:21:04.660+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [running]> on host 09c1abf4dbfb
[2025-04-12T13:21:04.728+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_comment_analysis_pipeline' AIRFLOW_CTX_TASK_ID='run_bertopic' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T00:00:00+00:00'
[2025-04-12T13:21:04.807+0000] {SentenceTransformer.py:208} INFO - Use pytorch device_name: cpu
[2025-04-12T13:21:04.808+0000] {SentenceTransformer.py:216} INFO - Load pretrained SentenceTransformer: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
[2025-04-12T13:22:55.690+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-04-12T13:22:55.708+0000] {process_utils.py:131} INFO - Sending 15 to group 54165. PIDs of all processes in the group: [54165]
[2025-04-12T13:22:55.708+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 54165
[2025-04-12T13:22:55.710+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-12T13:22:55.853+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=54165, status='terminated', exitcode=0, started='13:21:03') (54165) terminated with exit code 0
[2025-04-12T17:02:16.664+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-12T17:02:16.670+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-12T17:02:16.671+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-12T17:02:16.680+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_bertopic> on 2025-04-06 00:00:00+00:00
[2025-04-12T17:02:16.688+0000] {standard_task_runner.py:60} INFO - Started process 64012 to run task
[2025-04-12T17:02:16.691+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_comment_analysis_pipeline', 'run_bertopic', 'manual__2025-04-06T00:00:00+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/Sentiment_Topicmodelling.py', '--cfg-path', '/tmp/tmpdk_i368k']
[2025-04-12T17:02:16.693+0000] {standard_task_runner.py:88} INFO - Job 271: Subtask run_bertopic
[2025-04-12T17:02:16.729+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [running]> on host b22c3b1dd6e4
[2025-04-12T17:02:16.774+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_comment_analysis_pipeline' AIRFLOW_CTX_TASK_ID='run_bertopic' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T00:00:00+00:00'
[2025-04-12T17:02:16.832+0000] {SentenceTransformer.py:208} INFO - Use pytorch device_name: cpu
[2025-04-12T17:02:16.832+0000] {SentenceTransformer.py:216} INFO - Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2
[2025-04-12T17:46:09.511+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2025-04-12T17:46:09.515+0000] {process_utils.py:131} INFO - Sending 15 to group 64012. PIDs of all processes in the group: [64012]
[2025-04-12T17:46:09.516+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 64012
[2025-04-12T17:46:09.517+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-12T17:46:09.529+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Sentiment_Topicmodelling.py", line 92, in run_bertopic
    sentiment = analyze_sentiment(texts[i])
  File "/opt/airflow/dags/Sentiment_Topicmodelling.py", line 71, in analyze_sentiment
    outputs = model(**inputs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1668, in forward
    outputs = self.bert(
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1142, in forward
    encoder_outputs = self.encoder(
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/pytorch_utils.py", line 217, in apply_chunking_to_forward
    num_args_in_forward_chunk_fn = len(inspect.signature(forward_fn).parameters)
  File "/usr/local/lib/python3.8/inspect.py", line 3105, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/local/lib/python3.8/inspect.py", line 2854, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "/usr/local/lib/python3.8/inspect.py", line 2234, in _signature_from_callable
    obj.__func__,
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-04-12T17:46:09.538+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=weekly_comment_analysis_pipeline, task_id=run_bertopic, execution_date=20250406T000000, start_date=20250412T170216, end_date=20250412T174609
[2025-04-12T17:46:09.551+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 271 for task run_bertopic (Task received SIGTERM signal; 64012)
[2025-04-12T17:46:09.614+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=64012, status='terminated', exitcode=1, started='17:02:16') (64012) terminated with exit code 1
[2025-04-13T00:00:07.675+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-13T00:00:07.678+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-13T00:00:07.678+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-13T00:00:07.683+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_bertopic> on 2025-04-06 00:00:00+00:00
[2025-04-13T00:00:07.687+0000] {standard_task_runner.py:60} INFO - Started process 319 to run task
[2025-04-13T00:00:07.689+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_comment_analysis_pipeline', 'run_bertopic', 'manual__2025-04-06T00:00:00+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/Sentiment_Topicmodelling.py', '--cfg-path', '/tmp/tmpxi4b3h4s']
[2025-04-13T00:00:07.690+0000] {standard_task_runner.py:88} INFO - Job 285: Subtask run_bertopic
[2025-04-13T00:00:07.710+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_comment_analysis_pipeline.run_bertopic manual__2025-04-06T00:00:00+00:00 [running]> on host 61c0c751e7f9
[2025-04-13T00:00:07.740+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_comment_analysis_pipeline' AIRFLOW_CTX_TASK_ID='run_bertopic' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T00:00:00+00:00'
[2025-04-13T00:00:07.780+0000] {SentenceTransformer.py:208} INFO - Use pytorch device_name: cpu
[2025-04-13T00:00:07.780+0000] {SentenceTransformer.py:216} INFO - Load pretrained SentenceTransformer: sentence-transformers/all-MiniLM-L6-v2
[2025-04-13T00:03:03.993+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-04-13T00:03:03.997+0000] {process_utils.py:131} INFO - Sending 15 to group 319. PIDs of all processes in the group: [319]
[2025-04-13T00:03:03.998+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 319
[2025-04-13T00:03:04.000+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-13T00:03:04.010+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Sentiment_Topicmodelling.py", line 92, in run_bertopic
    enriched = []
  File "/opt/airflow/dags/Sentiment_Topicmodelling.py", line 71, in analyze_sentiment
    outputs = model(**inputs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1668, in forward
    outputs = self.bert(
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 1142, in forward
    encoder_outputs = self.encoder(
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 695, in forward
    layer_outputs = layer_module(
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 627, in forward
    layer_output = apply_chunking_to_forward(
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/pytorch_utils.py", line 248, in apply_chunking_to_forward
    return forward_fn(*input_tensors)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 639, in feed_forward_chunk
    intermediate_output = self.intermediate(attention_output)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/transformers/models/bert/modeling_bert.py", line 539, in forward
    hidden_states = self.dense(hidden_states)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 117, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-04-13T00:03:04.014+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=weekly_comment_analysis_pipeline, task_id=run_bertopic, execution_date=20250406T000000, start_date=20250413T000007, end_date=20250413T000304
[2025-04-13T00:03:04.020+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 285 for task run_bertopic (Task received SIGTERM signal; 319)
[2025-04-13T00:03:04.062+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=319, status='terminated', exitcode=1, started='00:00:06') (319) terminated with exit code 1
