[2025-04-13T04:32:47.608+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-13T04:32:47.611+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-06T00:00:00+00:00 [queued]>
[2025-04-13T04:32:47.611+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2025-04-13T04:32:47.616+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): save_processed_comments> on 2025-04-06 00:00:00+00:00
[2025-04-13T04:32:47.622+0000] {standard_task_runner.py:60} INFO - Started process 35664 to run task
[2025-04-13T04:32:47.624+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weekly_comment_analysis_pipeline', 'save_processed_comments', 'manual__2025-04-06T00:00:00+00:00', '--job-id', '317', '--raw', '--subdir', 'DAGS_FOLDER/Sentiment_Topicmodelling.py', '--cfg-path', '/tmp/tmpf23i65xt']
[2025-04-13T04:32:47.625+0000] {standard_task_runner.py:88} INFO - Job 317: Subtask save_processed_comments
[2025-04-13T04:32:47.647+0000] {task_command.py:423} INFO - Running <TaskInstance: weekly_comment_analysis_pipeline.save_processed_comments manual__2025-04-06T00:00:00+00:00 [running]> on host a33b1ed2b57f
[2025-04-13T04:32:47.674+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weekly_comment_analysis_pipeline' AIRFLOW_CTX_TASK_ID='save_processed_comments' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T00:00:00+00:00'
[2025-04-13T04:32:47.735+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-13T04:32:49.991+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:315 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-04-13T04:33:22.126+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-13T04:33:22.168+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weekly_comment_analysis_pipeline, task_id=save_processed_comments, execution_date=20250406T000000, start_date=20250413T043247, end_date=20250413T043322
[2025-04-13T04:33:22.242+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-13T04:33:22.286+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
