[2025-04-06T03:25:39.261+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres manual__2025-04-06T03:24:14.830488+00:00 [queued]>
[2025-04-06T03:25:39.265+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres manual__2025-04-06T03:24:14.830488+00:00 [queued]>
[2025-04-06T03:25:39.265+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-06T03:25:39.271+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-04-06 03:24:14.830488+00:00
[2025-04-06T03:25:39.274+0000] {standard_task_runner.py:60} INFO - Started process 2826 to run task
[2025-04-06T03:25:39.275+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'youtube_comment_pipeline_us_stocks_daily', 'load_to_postgres', 'manual__2025-04-06T03:24:14.830488+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comment_pipeline.py', '--cfg-path', '/tmp/tmpp792oszl']
[2025-04-06T03:25:39.277+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask load_to_postgres
[2025-04-06T03:25:39.300+0000] {task_command.py:423} INFO - Running <TaskInstance: youtube_comment_pipeline_us_stocks_daily.load_to_postgres manual__2025-04-06T03:24:14.830488+00:00 [running]> on host 04d9bebcd372
[2025-04-06T03:25:39.330+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_comment_pipeline_us_stocks_daily' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-06T03:24:14.830488+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-06T03:24:14.830488+00:00'
[2025-04-06T03:25:39.351+0000] {base.py:83} INFO - Using connection ID 'aws_pg' for task execution.
[2025-04-06T03:32:07.948+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-04-06T03:32:07.951+0000] {process_utils.py:131} INFO - Sending 15 to group 2826. PIDs of all processes in the group: [2826]
[2025-04-06T03:32:07.951+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2826
[2025-04-06T03:32:08.045+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-06T03:32:08.096+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2826, status='terminated', exitcode=0, started='03:25:38') (2826) terminated with exit code 0
